// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.0

package dbgen

type Note struct {
	ID          string
	WorkspaceID string
	Title       string
	Content     string
	CreatedAt   string
	UpdatedAt   string
}
