// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.0
// source: queries.sql

package dbgen

import (
	"context"
)

const countNotes = `-- name: CountNotes :one
SELECT count(*) FROM notes WHERE workspace_id = ?1
`

func (q *Queries) CountNotes(ctx context.Context, workspaceID string) (int64, error) {
	row := q.db.QueryRowContext(ctx, countNotes, workspaceID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createNote = `-- name: CreateNote :one
INSERT INTO notes (id, workspace_id, title, content, created_at, updated_at)
VALUES (?1, ?2, ?3, ?4, ?5, ?6)
RETURNING id, workspace_id, title, content, created_at, updated_at
`

type CreateNoteParams struct {
	ID          string
	WorkspaceID string
	Title       string
	Content     string
	CreatedAt   string
	UpdatedAt   string
}

func (q *Queries) CreateNote(ctx context.Context, arg CreateNoteParams) (Note, error) {
	row := q.db.QueryRowContext(ctx, createNote,
		arg.ID,
		arg.WorkspaceID,
		arg.Title,
		arg.Content,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	var i Note
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.Title,
		&i.Content,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteNote = `-- name: DeleteNote :execrows
DELETE FROM notes WHERE workspace_id = ?1 AND id = ?2
`

type DeleteNoteParams struct {
	WorkspaceID string
	ID          string
}

func (q *Queries) DeleteNote(ctx context.Context, arg DeleteNoteParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, deleteNote, arg.WorkspaceID, arg.ID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const getNote = `-- name: GetNote :one
SELECT id, workspace_id, title, content, created_at, updated_at FROM notes WHERE workspace_id = ?1 AND id = ?2
`

type GetNoteParams struct {
	WorkspaceID string
	ID          string
}

func (q *Queries) GetNote(ctx context.Context, arg GetNoteParams) (Note, error) {
	row := q.db.QueryRowContext(ctx, getNote, arg.WorkspaceID, arg.ID)
	var i Note
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.Title,
		&i.Content,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listNotes = `-- name: ListNotes :many
SELECT id, workspace_id, title, content, created_at, updated_at FROM notes WHERE workspace_id = ?1
ORDER BY created_at DESC, id DESC LIMIT ?3 OFFSET ?2
`

type ListNotesParams struct {
	WorkspaceID string
	PageOffset  int64
	PageSize    int64
}

func (q *Queries) ListNotes(ctx context.Context, arg ListNotesParams) ([]Note, error) {
	rows, err := q.db.QueryContext(ctx, listNotes, arg.WorkspaceID, arg.PageOffset, arg.PageSize)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Note{}
	for rows.Next() {
		var i Note
		if err := rows.Scan(
			&i.ID,
			&i.WorkspaceID,
			&i.Title,
			&i.Content,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateNote = `-- name: UpdateNote :one
UPDATE notes SET title = ?1, content = ?2, updated_at = ?3
WHERE workspace_id = ?4 AND id = ?5
RETURNING id, workspace_id, title, content, created_at, updated_at
`

type UpdateNoteParams struct {
	Title       string
	Content     string
	UpdatedAt   string
	WorkspaceID string
	ID          string
}

func (q *Queries) UpdateNote(ctx context.Context, arg UpdateNoteParams) (Note, error) {
	row := q.db.QueryRowContext(ctx, updateNote,
		arg.Title,
		arg.Content,
		arg.UpdatedAt,
		arg.WorkspaceID,
		arg.ID,
	)
	var i Note
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.Title,
		&i.Content,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
