// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.0
// source: queries.sql

package dbgen

import (
	"context"
)

const createOwnerMembership = `-- name: CreateOwnerMembership :exec
INSERT INTO workspace_members (workspace_id, user_id, role)
VALUES (?1, ?2, 'owner')
`

type CreateOwnerMembershipParams struct {
	WorkspaceID string
	UserID      string
}

func (q *Queries) CreateOwnerMembership(ctx context.Context, arg CreateOwnerMembershipParams) error {
	_, err := q.db.ExecContext(ctx, createOwnerMembership, arg.WorkspaceID, arg.UserID)
	return err
}

const createWorkspace = `-- name: CreateWorkspace :exec
INSERT INTO workspaces (id, name, created_at)
VALUES (?1, ?2, ?3)
`

type CreateWorkspaceParams struct {
	ID        string
	Name      string
	CreatedAt string
}

func (q *Queries) CreateWorkspace(ctx context.Context, arg CreateWorkspaceParams) error {
	_, err := q.db.ExecContext(ctx, createWorkspace, arg.ID, arg.Name, arg.CreatedAt)
	return err
}

const getRole = `-- name: GetRole :one
SELECT role FROM workspace_members
WHERE workspace_id = ?1 AND user_id = ?2
`

type GetRoleParams struct {
	WorkspaceID string
	UserID      string
}

func (q *Queries) GetRole(ctx context.Context, arg GetRoleParams) (string, error) {
	row := q.db.QueryRowContext(ctx, getRole, arg.WorkspaceID, arg.UserID)
	var role string
	err := row.Scan(&role)
	return role, err
}

const listWorkspaces = `-- name: ListWorkspaces :many
SELECT w.id, w.name, m.role FROM workspaces w
JOIN workspace_members m ON m.workspace_id = w.id
WHERE m.user_id = ?1 ORDER BY w.created_at, w.id
`

type ListWorkspacesRow struct {
	ID   string
	Name string
	Role string
}

func (q *Queries) ListWorkspaces(ctx context.Context, userID string) ([]ListWorkspacesRow, error) {
	rows, err := q.db.QueryContext(ctx, listWorkspaces, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListWorkspacesRow{}
	for rows.Next() {
		var i ListWorkspacesRow
		if err := rows.Scan(&i.ID, &i.Name, &i.Role); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
