// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.0
// source: queries.sql

package dbgen

import (
	"context"
	"database/sql"
)

const appendEvent = `-- name: AppendEvent :exec
INSERT INTO events(id,run_id,seq,kind,payload_json,created_at)
VALUES(?1,?2,?3,?4,?5,?6)
`

type AppendEventParams struct {
	ID          string
	RunID       string
	Seq         int64
	Kind        string
	PayloadJson string
	CreatedAt   string
}

func (q *Queries) AppendEvent(ctx context.Context, arg AppendEventParams) error {
	_, err := q.db.ExecContext(ctx, appendEvent,
		arg.ID,
		arg.RunID,
		arg.Seq,
		arg.Kind,
		arg.PayloadJson,
		arg.CreatedAt,
	)
	return err
}

const conversationRuns = `-- name: ConversationRuns :many
SELECT id, title, scenario_id, mode, status, protocol_version, agent_type, created_at, finished_at, last_seq, conversation_id, turn_index FROM runs WHERE conversation_id=?1 ORDER BY turn_index
`

func (q *Queries) ConversationRuns(ctx context.Context, conversationID sql.NullString) ([]Run, error) {
	rows, err := q.db.QueryContext(ctx, conversationRuns, conversationID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Run{}
	for rows.Next() {
		var i Run
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.ScenarioID,
			&i.Mode,
			&i.Status,
			&i.ProtocolVersion,
			&i.AgentType,
			&i.CreatedAt,
			&i.FinishedAt,
			&i.LastSeq,
			&i.ConversationID,
			&i.TurnIndex,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const createConversation = `-- name: CreateConversation :exec
INSERT INTO conversations(id,title,created_at) VALUES(?1,?2,?3)
`

type CreateConversationParams struct {
	ID        string
	Title     string
	CreatedAt string
}

func (q *Queries) CreateConversation(ctx context.Context, arg CreateConversationParams) error {
	_, err := q.db.ExecContext(ctx, createConversation, arg.ID, arg.Title, arg.CreatedAt)
	return err
}

const createRun = `-- name: CreateRun :one
INSERT INTO runs(id,title,scenario_id,mode,status,protocol_version,agent_type,created_at,conversation_id,turn_index)
VALUES(?1,?2,?3,'deterministic','running',?4,'mock',?5,?6,?7) RETURNING id, title, scenario_id, mode, status, protocol_version, agent_type, created_at, finished_at, last_seq, conversation_id, turn_index
`

type CreateRunParams struct {
	ID              string
	Title           string
	ScenarioID      string
	ProtocolVersion string
	CreatedAt       string
	ConversationID  sql.NullString
	TurnIndex       int64
}

func (q *Queries) CreateRun(ctx context.Context, arg CreateRunParams) (Run, error) {
	row := q.db.QueryRowContext(ctx, createRun,
		arg.ID,
		arg.Title,
		arg.ScenarioID,
		arg.ProtocolVersion,
		arg.CreatedAt,
		arg.ConversationID,
		arg.TurnIndex,
	)
	var i Run
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.ScenarioID,
		&i.Mode,
		&i.Status,
		&i.ProtocolVersion,
		&i.AgentType,
		&i.CreatedAt,
		&i.FinishedAt,
		&i.LastSeq,
		&i.ConversationID,
		&i.TurnIndex,
	)
	return i, err
}

const deleteAllRuns = `-- name: DeleteAllRuns :execrows
DELETE FROM runs
`

func (q *Queries) DeleteAllRuns(ctx context.Context) (int64, error) {
	result, err := q.db.ExecContext(ctx, deleteAllRuns)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const deleteEmptyConversations = `-- name: DeleteEmptyConversations :exec
DELETE FROM conversations WHERE NOT EXISTS (SELECT 1 FROM runs WHERE runs.conversation_id=conversations.id)
`

func (q *Queries) DeleteEmptyConversations(ctx context.Context) error {
	_, err := q.db.ExecContext(ctx, deleteEmptyConversations)
	return err
}

const deleteRun = `-- name: DeleteRun :execrows
DELETE FROM runs WHERE id=?1 AND status!='running'
`

func (q *Queries) DeleteRun(ctx context.Context, id string) (int64, error) {
	result, err := q.db.ExecContext(ctx, deleteRun, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const getRun = `-- name: GetRun :one
SELECT id, title, scenario_id, mode, status, protocol_version, agent_type, created_at, finished_at, last_seq, conversation_id, turn_index FROM runs WHERE id=?1
`

func (q *Queries) GetRun(ctx context.Context, id string) (Run, error) {
	row := q.db.QueryRowContext(ctx, getRun, id)
	var i Run
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.ScenarioID,
		&i.Mode,
		&i.Status,
		&i.ProtocolVersion,
		&i.AgentType,
		&i.CreatedAt,
		&i.FinishedAt,
		&i.LastSeq,
		&i.ConversationID,
		&i.TurnIndex,
	)
	return i, err
}

const listEvents = `-- name: ListEvents :many
SELECT id, run_id, seq, kind, payload_json, created_at FROM events WHERE run_id=?1 AND seq>?2 ORDER BY seq LIMIT ?3
`

type ListEventsParams struct {
	RunID    string
	AfterSeq int64
	PageSize int64
}

func (q *Queries) ListEvents(ctx context.Context, arg ListEventsParams) ([]Event, error) {
	rows, err := q.db.QueryContext(ctx, listEvents, arg.RunID, arg.AfterSeq, arg.PageSize)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Event{}
	for rows.Next() {
		var i Event
		if err := rows.Scan(
			&i.ID,
			&i.RunID,
			&i.Seq,
			&i.Kind,
			&i.PayloadJson,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRuns = `-- name: ListRuns :many
SELECT id, title, scenario_id, mode, status, protocol_version, agent_type, created_at, finished_at, last_seq, conversation_id, turn_index FROM runs ORDER BY created_at DESC,id LIMIT ?2 OFFSET ?1
`

type ListRunsParams struct {
	PageOffset int64
	PageSize   int64
}

func (q *Queries) ListRuns(ctx context.Context, arg ListRunsParams) ([]Run, error) {
	rows, err := q.db.QueryContext(ctx, listRuns, arg.PageOffset, arg.PageSize)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Run{}
	for rows.Next() {
		var i Run
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.ScenarioID,
			&i.Mode,
			&i.Status,
			&i.ProtocolVersion,
			&i.AgentType,
			&i.CreatedAt,
			&i.FinishedAt,
			&i.LastSeq,
			&i.ConversationID,
			&i.TurnIndex,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const runningRuns = `-- name: RunningRuns :many
SELECT id, title, scenario_id, mode, status, protocol_version, agent_type, created_at, finished_at, last_seq, conversation_id, turn_index FROM runs WHERE status='running'
`

func (q *Queries) RunningRuns(ctx context.Context) ([]Run, error) {
	rows, err := q.db.QueryContext(ctx, runningRuns)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Run{}
	for rows.Next() {
		var i Run
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.ScenarioID,
			&i.Mode,
			&i.Status,
			&i.ProtocolVersion,
			&i.AgentType,
			&i.CreatedAt,
			&i.FinishedAt,
			&i.LastSeq,
			&i.ConversationID,
			&i.TurnIndex,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateRun = `-- name: UpdateRun :exec
UPDATE runs SET last_seq=?1,status=?2,finished_at=?3 WHERE id=?4
`

type UpdateRunParams struct {
	LastSeq    int64
	Status     string
	FinishedAt string
	ID         string
}

func (q *Queries) UpdateRun(ctx context.Context, arg UpdateRunParams) error {
	_, err := q.db.ExecContext(ctx, updateRun,
		arg.LastSeq,
		arg.Status,
		arg.FinishedAt,
		arg.ID,
	)
	return err
}
