// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.0
// source: queries.sql

package dbgen

import (
	"context"
)

const createAdminMembership = `-- name: CreateAdminMembership :exec
INSERT INTO workspace_members (workspace_id, user_id, role)
VALUES (?1, ?2, 'owner')
`

type CreateAdminMembershipParams struct {
	WorkspaceID string
	UserID      string
}

func (q *Queries) CreateAdminMembership(ctx context.Context, arg CreateAdminMembershipParams) error {
	_, err := q.db.ExecContext(ctx, createAdminMembership, arg.WorkspaceID, arg.UserID)
	return err
}

const createAdminUser = `-- name: CreateAdminUser :execrows
INSERT INTO users (id, email, password_hash, created_at)
VALUES (?1, ?2, ?3, ?4)
ON CONFLICT(email) DO NOTHING
`

type CreateAdminUserParams struct {
	ID           string
	Email        string
	PasswordHash string
	CreatedAt    string
}

func (q *Queries) CreateAdminUser(ctx context.Context, arg CreateAdminUserParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, createAdminUser,
		arg.ID,
		arg.Email,
		arg.PasswordHash,
		arg.CreatedAt,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const createAdminWorkspace = `-- name: CreateAdminWorkspace :exec
INSERT INTO workspaces (id, name, created_at)
VALUES (?1, ?2, ?3)
`

type CreateAdminWorkspaceParams struct {
	ID        string
	Name      string
	CreatedAt string
}

func (q *Queries) CreateAdminWorkspace(ctx context.Context, arg CreateAdminWorkspaceParams) error {
	_, err := q.db.ExecContext(ctx, createAdminWorkspace, arg.ID, arg.Name, arg.CreatedAt)
	return err
}

const deleteExpiredSessions = `-- name: DeleteExpiredSessions :exec
DELETE FROM sessions WHERE expires_at <= ?1
`

func (q *Queries) DeleteExpiredSessions(ctx context.Context, expiresAt int64) error {
	_, err := q.db.ExecContext(ctx, deleteExpiredSessions, expiresAt)
	return err
}

const deleteSession = `-- name: DeleteSession :exec
DELETE FROM sessions WHERE token_hash = ?1
`

func (q *Queries) DeleteSession(ctx context.Context, tokenHash string) error {
	_, err := q.db.ExecContext(ctx, deleteSession, tokenHash)
	return err
}

const getCredentials = `-- name: GetCredentials :one
SELECT id, email, password_hash FROM users WHERE email = ?1
`

type GetCredentialsRow struct {
	ID           string
	Email        string
	PasswordHash string
}

func (q *Queries) GetCredentials(ctx context.Context, email string) (GetCredentialsRow, error) {
	row := q.db.QueryRowContext(ctx, getCredentials, email)
	var i GetCredentialsRow
	err := row.Scan(&i.ID, &i.Email, &i.PasswordHash)
	return i, err
}

const getSession = `-- name: GetSession :one
SELECT u.id, u.email, s.csrf_token, s.expires_at FROM sessions s
JOIN users u ON u.id = s.user_id
WHERE s.token_hash = ?1 AND s.expires_at > ?2
`

type GetSessionParams struct {
	TokenHash string
	ExpiresAt int64
}

type GetSessionRow struct {
	ID        string
	Email     string
	CSRFToken string
	ExpiresAt int64
}

func (q *Queries) GetSession(ctx context.Context, arg GetSessionParams) (GetSessionRow, error) {
	row := q.db.QueryRowContext(ctx, getSession, arg.TokenHash, arg.ExpiresAt)
	var i GetSessionRow
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.CSRFToken,
		&i.ExpiresAt,
	)
	return i, err
}

const saveSession = `-- name: SaveSession :exec
INSERT INTO sessions (token_hash, user_id, csrf_token, expires_at)
VALUES (?1, ?2, ?3, ?4)
`

type SaveSessionParams struct {
	TokenHash string
	UserID    string
	CSRFToken string
	ExpiresAt int64
}

func (q *Queries) SaveSession(ctx context.Context, arg SaveSessionParams) error {
	_, err := q.db.ExecContext(ctx, saveSession,
		arg.TokenHash,
		arg.UserID,
		arg.CSRFToken,
		arg.ExpiresAt,
	)
	return err
}

const trimUserSessions = `-- name: TrimUserSessions :exec
DELETE FROM sessions WHERE sessions.user_id = ?1
AND sessions.token_hash NOT IN (
  SELECT kept.token_hash FROM sessions AS kept WHERE kept.user_id = ?1
  ORDER BY kept.expires_at DESC LIMIT 9
)
`

func (q *Queries) TrimUserSessions(ctx context.Context, userID string) error {
	_, err := q.db.ExecContext(ctx, trimUserSessions, userID)
	return err
}
